
-- 1. Bảng loại hàng
CREATE TABLE Category (
                          category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_name VARCHAR2(100) NOT NULL
);

-- 2. Bảng hàng hóa
CREATE TABLE Product (
                         product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR2(255) NOT NULL,
                         price NUMBER(10, 2) NOT NULL,
                         quantity NUMBER DEFAULT 0,
                         category_id NUMBER NOT NULL,
                         description VARCHAR2(1000),
                         image_url VARCHAR2(255),
                         created_at DATE DEFAULT SYSDATE,
                         is_hot NUMBER(1) DEFAULT 0,
                         is_discount NUMBER(1) DEFAULT 0,
                         is_new NUMBER(1) DEFAULT 0,
                         FOREIGN KEY (category_id) REFERENCES Category(category_id)
);


-- 3. Bảng người dùng
CREATE TABLE UserAccount (
                             user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             username VARCHAR2(50) UNIQUE NOT NULL,
                             password VARCHAR2(255) NOT NULL,
                             email VARCHAR2(100) UNIQUE NOT NULL,
                             full_name VARCHAR2(100),
                             phone VARCHAR2(20),
                             address VARCHAR2(255),
                             role VARCHAR2(20) DEFAULT 'USER', -- USER / ADMIN
                             is_active NUMBER(1) DEFAULT 0,
                             activation_token VARCHAR2(100),
                             reset_token VARCHAR2(100),
                             created_at DATE DEFAULT SYSDATE
);

-- 4. Bảng đơn hàng
CREATE TABLE OrderTable (
                            order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id NUMBER NOT NULL,
                            order_date DATE DEFAULT SYSDATE,
                            status VARCHAR2(50) DEFAULT 'PENDING', -- PENDING, PAID, SHIPPED, CANCELED
                            total_amount NUMBER(10, 2),
                            FOREIGN KEY (user_id) REFERENCES UserAccount(user_id)
);

-- 5. Bảng chi tiết đơn hàng
CREATE TABLE OrderDetail (
                             order_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id NUMBER NOT NULL,
                             product_id NUMBER NOT NULL,
                             quantity NUMBER NOT NULL,
                             price NUMBER(10, 2) NOT NULL,
                             FOREIGN KEY (order_id) REFERENCES OrderTable(order_id),
                             FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

-- 6. Bảng giỏ hàng
CREATE TABLE Cart (
                      cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id NUMBER NOT NULL,
                      created_at DATE DEFAULT SYSDATE,
                      FOREIGN KEY (user_id) REFERENCES UserAccount(user_id)
);

-- 7. Bảng chi tiết giỏ hàng
CREATE TABLE CartItem (
                          cart_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          cart_id NUMBER NOT NULL,
                          product_id NUMBER NOT NULL,
                          quantity NUMBER NOT NULL,
                          FOREIGN KEY (cart_id) REFERENCES Cart(cart_id),
                          FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

INSERT INTO Category (category_name) VALUES
    ('Điện thoại');
INSERT INTO Category (category_name) VALUES
    ('Laptop');
INSERT INTO Category (category_name) VALUES
    ('Máy tính bảng');
INSERT INTO Category (category_name) VALUES
    ('Phụ kiện');
INSERT INTO Category (category_name) VALUES
    ('Đồng hồ');
INSERT INTO Category (category_name) VALUES
    ('TV & Màn hình');
INSERT INTO Category (category_name) VALUES
    ('Loa & Âm thanh');
INSERT INTO Category (category_name) VALUES
    ('Thiết bị văn phòng');
INSERT INTO Category (category_name) VALUES
    ('Đồ chơi công nghệ');
INSERT INTO Category (category_name) VALUES
    ('Gia dụng thông minh');


ALTER TABLE CATEGORY
    ADD (DESCRIPTION VARCHAR2(255));

ALTER TABLE PRODUCT
    ADD (
        DISCOUNT_PERCENT NUMBER(5, 2) DEFAULT 0,
        RATING           NUMBER(2, 1) DEFAULT 0
        );



ALTER TABLE USERACCOUNT
ADD IS_VERIFIED Number(1) DEFAULT 0;


ALTER TABLE USERACCOUNT
    MODIFY (ACTIVATION_TOKEN VARCHAR2(512));

ALTER TABLE ordertable MODIFY total_amount NUMBER(12,2);

ALTER TABLE ORDERTABLE
    ADD (
        PAYMENT_METHOD   VARCHAR2(50),
        RECEIVER_NAME    VARCHAR2(100),
        RECEIVER_PHONE   VARCHAR2(20),
        RECEIVER_ADDRESS VARCHAR2(255)
        );

ALTER TABLE USERACCOUNT
    ADD (
        IS_GOOGLE_USER  NUMBER(1) DEFAULT 0);




ALTER TABLE ORDERDETAIL
    ADD CONSTRAINT FK_ORDERDETAIL_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES PRODUCT(PRODUCT_ID)
                ON DELETE CASCADE;