
-- 1. Bảng loại hàng
CREATE TABLE Category (
                          category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_name VARCHAR2(100) NOT NULL
);

-- 2. Bảng hàng hóa
CREATE TABLE Product (
                         product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR2(255) NOT NULL,
                         price NUMBER(10, 2) NOT NULL,
                         quantity NUMBER DEFAULT 0,
                         category_id NUMBER NOT NULL,
                         description VARCHAR2(1000),
                         image_url VARCHAR2(255),
                         created_at DATE DEFAULT SYSDATE,
                         is_hot NUMBER(1) DEFAULT 0,
                         is_discount NUMBER(1) DEFAULT 0,
                         is_new NUMBER(1) DEFAULT 0,
                         FOREIGN KEY (category_id) REFERENCES Category(category_id)
);

-- 3. Bảng người dùng
CREATE TABLE UserAccount (
                             user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             username VARCHAR2(50) UNIQUE NOT NULL,
                             password VARCHAR2(255) NOT NULL,
                             email VARCHAR2(100) UNIQUE NOT NULL,
                             full_name VARCHAR2(100),
                             phone VARCHAR2(20),
                             address VARCHAR2(255),
                             role VARCHAR2(20) DEFAULT 'USER', -- USER / ADMIN
                             is_active NUMBER(1) DEFAULT 0,
                             activation_token VARCHAR2(100),
                             reset_token VARCHAR2(100),
                             created_at DATE DEFAULT SYSDATE
);

-- 4. Bảng đơn hàng
CREATE TABLE OrderTable (
                            order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id NUMBER NOT NULL,
                            order_date DATE DEFAULT SYSDATE,
                            status VARCHAR2(50) DEFAULT 'PENDING', -- PENDING, PAID, SHIPPED, CANCELED
                            total_amount NUMBER(10, 2),
                            FOREIGN KEY (user_id) REFERENCES UserAccount(user_id)
);

-- 5. Bảng chi tiết đơn hàng
CREATE TABLE OrderDetail (
                             order_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id NUMBER NOT NULL,
                             product_id NUMBER NOT NULL,
                             quantity NUMBER NOT NULL,
                             price NUMBER(10, 2) NOT NULL,
                             FOREIGN KEY (order_id) REFERENCES OrderTable(order_id),
                             FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

-- 6. Bảng giỏ hàng
CREATE TABLE Cart (
                      cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id NUMBER NOT NULL,
                      created_at DATE DEFAULT SYSDATE,
                      FOREIGN KEY (user_id) REFERENCES UserAccount(user_id)
);

-- 7. Bảng chi tiết giỏ hàng
CREATE TABLE CartItem (
                          cart_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          cart_id NUMBER NOT NULL,
                          product_id NUMBER NOT NULL,
                          quantity NUMBER NOT NULL,
                          FOREIGN KEY (cart_id) REFERENCES Cart(cart_id),
                          FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

INSERT INTO Category (category_name) VALUES
    ('Điện thoại');
INSERT INTO Category (category_name) VALUES
    ('Laptop');
INSERT INTO Category (category_name) VALUES
    ('Máy tính bảng');
INSERT INTO Category (category_name) VALUES
    ('Phụ kiện');
INSERT INTO Category (category_name) VALUES
    ('Đồng hồ');
INSERT INTO Category (category_name) VALUES
    ('TV & Màn hình');
INSERT INTO Category (category_name) VALUES
    ('Loa & Âm thanh');
INSERT INTO Category (category_name) VALUES
    ('Thiết bị văn phòng');
INSERT INTO Category (category_name) VALUES
    ('Đồ chơi công nghệ');
INSERT INTO Category (category_name) VALUES
    ('Gia dụng thông minh');

INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('iPhone 15 Pro', 29990000, 10, 1, 'Điện thoại cao cấp từ Apple', 'iphone15.jpg', 1, 0, 1);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('Samsung Galaxy S23', 22990000, 15, 1, 'Flagship của Samsung', 's23.jpg', 1, 1, 1);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('MacBook Air M2', 24990000, 8, 2, 'Laptop mỏng nhẹ, chip M2', 'macairm2.jpg', 1, 1, 1);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('Dell XPS 13', 27990000, 5, 2, 'Laptop cao cấp của Dell', 'dellxps.jpg', 0, 1, 0);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('iPad Pro 11"', 21990000, 7, 3, 'Máy tính bảng hiệu suất cao', 'ipadpro.jpg', 1, 0, 1);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('AirPods Pro 2', 5990000, 20, 4, 'Tai nghe không dây Apple', 'airpodspro2.jpg', 1, 0, 1);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('Apple Watch Series 9', 10990000, 12, 5, 'Đồng hồ thông minh Apple', 'aw9.jpg', 1, 1, 1);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('Sony WH-1000XM5', 8990000, 10, 7, 'Tai nghe chống ồn cao cấp', 'sonyxm5.jpg', 1, 1, 0);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('Logitech MX Master 3', 2290000, 25, 4, 'Chuột không dây văn phòng', 'mx3.jpg', 0, 1, 0);
INSERT INTO Product (name, price, quantity, category_id, description, image_url, is_hot, is_discount, is_new) VALUES
    ('Máy in Canon LBP2900', 3690000, 6, 8, 'Máy in văn phòng phổ biến', 'canon2900.jpg', 0, 0, 0);

INSERT INTO UserAccount (username, password, email, full_name, phone, address, role, is_active) VALUES
    ('admin', 'admin123', 'admin@example.com', 'Quản trị viên', '0123456789', 'Hà Nội', 'ADMIN', 1);
INSERT INTO UserAccount (username, password, email, full_name, phone, address, is_active) VALUES
    ('user01', 'pass01', 'user01@gmail.com', 'Nguyễn Văn A', '0901123456', 'HCM', 1);
INSERT INTO UserAccount (username, password, email, full_name, phone, address, is_active) VALUES
    ('user02', 'pass02', 'user02@gmail.com', 'Trần Thị B', '0902123456', 'Đà Nẵng', 1);
INSERT INTO UserAccount (username, password, email, full_name, phone, address) VALUES
    ('user03', 'pass03', 'user03@gmail.com', 'Lê Văn C', '0903123456', 'Cần Thơ');
INSERT INTO UserAccount (username, password, email, full_name, phone, address) VALUES
    ('user04', 'pass04', 'user04@gmail.com', 'Phạm Thị D', '0904123456', 'Hà Nội');
INSERT INTO UserAccount (username, password, email, full_name, phone, address, is_active) VALUES
    ('user05', 'pass05', 'user05@gmail.com', 'Võ Văn E', '0905123456', 'Bình Dương', 1);
INSERT INTO UserAccount (username, password, email, full_name, phone, address) VALUES
    ('user06', 'pass06', 'user06@gmail.com', 'Hoàng Thị F', '0906123456', 'Nha Trang');
INSERT INTO UserAccount (username, password, email, full_name, phone, address) VALUES
    ('user07', 'pass07', 'user07@gmail.com', 'Mai Văn G', '0907123456', 'Huế');
INSERT INTO UserAccount (username, password, email, full_name, phone, address) VALUES
    ('user08', 'pass08', 'user08@gmail.com', 'Đinh Thị H', '0908123456', 'Quảng Ninh');
INSERT INTO UserAccount (username, password, email, full_name, phone, address) VALUES
    ('user09', 'pass09', 'user09@gmail.com', 'Ngô Văn I', '0909123456', 'Đồng Nai');

INSERT INTO OrderTable (user_id, status, total_amount) VALUES (2, 'PENDING', 5990000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (3, 'PAID', 8990000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (4, 'SHIPPED', 29990000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (5, 'CANCELED', 22990000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (6, 'PAID', 3690000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (7, 'PENDING', 2290000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (8, 'SHIPPED', 10990000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (9, 'PAID', 24990000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (3, 'PENDING', 21990000);
INSERT INTO OrderTable (user_id, status, total_amount) VALUES (2, 'SHIPPED', 27990000);

INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (1, 6, 1, 5990000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (2, 8, 1, 8990000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (3, 1, 1, 29990000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (4, 2, 1, 22990000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (5, 10, 1, 3690000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (6, 9, 1, 2290000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (7, 7, 1, 10990000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (8, 3, 1, 24990000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (9, 5, 1, 21990000);
INSERT INTO OrderDetail (order_id, product_id, quantity, price) VALUES (10, 4, 1, 27990000);


INSERT INTO Cart (user_id) VALUES (2);
INSERT INTO Cart (user_id) VALUES (3);
INSERT INTO Cart (user_id) VALUES (4);
INSERT INTO Cart (user_id) VALUES (5);
INSERT INTO Cart (user_id) VALUES (6);
INSERT INTO Cart (user_id) VALUES (7);
INSERT INTO Cart (user_id) VALUES (8);
INSERT INTO Cart (user_id) VALUES (9);
INSERT INTO Cart (user_id) VALUES (3);
INSERT INTO Cart (user_id) VALUES (2);

INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (1, 6, 1);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (2, 8, 1);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (3, 1, 2);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (4, 2, 1);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (5, 9, 2);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (6, 7, 1);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (7, 3, 1);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (8, 5, 1);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (9, 4, 1);
INSERT INTO CartItem (cart_id, product_id, quantity) VALUES (10, 10, 1);

COMMIT;
