server:
  port: 9999

spring:
  application:
    name: VitaminCode_BE

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: POLY_OE
    password: T2403

  security:
    user:
      name: admin
      password: 123
      roles: ADMIN
