server:
  port: 1903

spring:
  application:
    name: Jerry
  liquibase:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: url-database-server
    username: username
    password: password
