server:
  port: 1903

spring:
  application:
    name: Jerry
  liquibase:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: trantuan88261@gmail.com
    password: sqsokrgfjqhynshq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: POLY_OE
    password: T2403

  jpa:
    open-in-view: false

  thymeleaf:
    check-template-location: false

  devtools:
    add-properties: false

logging:
  level:
    org.hibernate: warn
    org.hibernate.orm.connections.pooling: warn

jwt:
  secret-key: "YHeTykc90EQL7tozCEbrLoTVpZ/PxtOQ/MyoDDfaS20k+lHHFVXyVp7vviKI9dEm"
