server:
  port: 1903

spring:
  application:
    name: Jerry
  liquibase:
    enabled: false

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: POLY_OE
    password: T2403

  jpa:
    open-in-view: false

  thymeleaf:
    check-template-location: false

  devtools:
    add-properties: false

jwt:
  secret-key: "YHeTykc90EQL7tozCEbrLoTVpZ/PxtOQ/MyoDDfaS20k+lHHFVXyVp7vviKI9dEm"
